// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vedy.Infrastructure.Persistence;

#nullable disable

namespace Vedy.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250111160659_AddDataForUsers")]
    partial class AddDataForUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vedy.Data.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Tin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Vedy.Data.CustomerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("SettlementId")
                        .HasColumnType("bigint");

                    b.Property<string>("SignHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Sum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SettlementId");

                    b.ToTable("CustomerEntries");
                });

            modelBuilder.Entity("Vedy.Data.Settlement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("Vedy.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FullName = "Administrator",
                            IsDeleted = false,
                            Login = "admin",
                            Password = "4DA881DECEE92CA3B577F188EAAF92265A5550AF85F391CEB1FBE26A1C72F3E29AF139B1F941CDE4AA64C70CE01BACC3DE4F6F6657BF33CFCAA91EB27CB03EC4",
                            Role = 1
                        },
                        new
                        {
                            Id = 2L,
                            FullName = "Operator",
                            IsDeleted = false,
                            Login = "operator",
                            Password = "990B065EF6ECA1303AF386821A61AB374CC412D7C482967086505ACA1295FBF8641DE8F3F0B020E4760A65F55AD7C898351626CDEDF5DAF5683D334B0DC68E2F",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Vedy.Data.CustomerEntry", b =>
                {
                    b.HasOne("Vedy.Data.Company", "Company")
                        .WithMany("CustomerEntries")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Vedy.Data.Settlement", "Settlement")
                        .WithMany("CustomerEntries")
                        .HasForeignKey("SettlementId");

                    b.Navigation("Company");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Vedy.Data.Settlement", b =>
                {
                    b.HasOne("Vedy.Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("Vedy.Data.User", "User")
                        .WithMany("Settlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vedy.Data.Company", b =>
                {
                    b.Navigation("CustomerEntries");
                });

            modelBuilder.Entity("Vedy.Data.Settlement", b =>
                {
                    b.Navigation("CustomerEntries");
                });

            modelBuilder.Entity("Vedy.Data.User", b =>
                {
                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
